version: '3'

services:
  cassandra-node1:
    image: cassandra:latest
    container_name: ntsoekhe-node1
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
    networks:
      - cassandra-net

  cassandra-node2:
    image: cassandra:latest
    container_name: ntsoekhe-node2
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
    networks:
      - cassandra-net

  cassandra-node3:
    image: cassandra:latest
    container_name: ntsoekhe-node3
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
    networks:
      - cassandra-net

networks:
  cassandra-net:
    driver: bridge
